### ISSUE TITLE
Change the static fixtures path to a dynamic one

### ISSUE THREAD

**Issue by tuxiqae** [MikeWalrus/docx-you-want#1]
https://github.com/MikeWalrus/docx-you-want/blob/33d38ac11bf3b803ed0ca23b1a6d495894553721/src/lib.rs#L134

**Comment by MikeWalrus** [comment]
Thanks, I forgot about that.

**Comment by MikeWalrus** [comment]
Is it OK to bundle the files using `include_bytes!`?

**Comment by tuxiqae** [comment]
What is the purpose of those files?

**Comment by MikeWalrus** [comment]
That's the files you'll get if you unzip a docx. I just use a minimum version of those and insert information about the images into some of the XMLs.
